version: "2.2"

services:
  PostgreSQL_for_Grocery_Store:
    image: ${IMAGE_HOST}postgressql_for_grocery_store
    environment:
      POSTGRES_PASSWORD:
    restart: always
  Grocery_Store:
    image: ${IMAGE_HOST}grocery_store
    depends_on:
      - PostgreSQL_for_Grocery_Store
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - PostgreSQL_for_Grocery_Store:${PGHOST}
    restart: always
